config/routes.rb
Rails.application.routes.draw do
  resources :categories
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :estimates
  resources :projects
  resources :project_titans
  resources :titan_roles
  resources :roles
  resources :sows
  resources :clients
  resources :titans
  resources :offices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :subcategories, :class_name => "Category", :foreign_key => "parent_id", :dependent => :destroy
  belongs_to :parent_category, :class_name => "Category", optional: true

   accepts_nested_attributes_for :subcategories
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :office, inverse_of: :clients
  has_many :projects, inverse_of: :client
end

app/models/estimate.rb
class Estimate < ApplicationRecord
  belongs_to :project, inverse_of: :estimate
end

app/models/office.rb
class Office < ApplicationRecord
	has_many :clients
	has_many :projects, through: :clients
	has_many :sows, through: :projects
	has_many :estimates, through: :projects


	has_many :titans

	enum name: {east: 'East Coast', west: 'West Coast', central: 'Dallas'}

end

app/models/project.rb
class Project < ApplicationRecord

  belongs_to :client, inverse_of: :projects
  has_one :sow, inverse_of: :project
  has_one :estimate, inverse_of: :project
  has_many :project_titans, inverse_of: :titan
  has_many :titans, through: :project_titans


  accepts_nested_attributes_for :sow, :estimate 

  enum phase: {
  	bd: 'BizDev', 
  	pitch: 'Pitched', 
  	negotiation: 'Drafting / SOW Negoiation', 
  	accepted: 'Accepted', 
  	in_progress: 'In Progress', 
  	complete: 'Completed', 
  	archived: 'Rejected'
  }

  enum category: {
    Strategy_Operationalization: 'Strategy Operationalization', 
    Operating_Model_Agility: 'Operating Model Agility', 
    Strategy_Development: 'Strategy Development', 
    Digital_and_Tech_Transformation: 'Digital & Tech Transformation', 
  }
  
end

app/models/project_titan.rb
class ProjectTitan < ApplicationRecord
  belongs_to :project
  belongs_to :titan
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :titan_roles
	has_many :titans, through: :titan_roles

end

app/models/sow.rb
class Sow < ApplicationRecord
  belongs_to :project, inverse_of: :sow
end

app/models/titan.rb
class Titan < ApplicationRecord
	belongs_to :office

	
	
	has_many :project_titans
	has_many :projects, through: :project_titans
	has_many :clients, through: :projects

	has_many :titan_roles
	has_many :roles, through: :titan_roles
end

app/models/titan_role.rb
class TitanRole < ApplicationRecord
  belongs_to :titan
  belongs_to :role
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: [:show, :edit, :update, :destroy]

  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.all
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: 'Office was successfully created.' }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, notice: 'Office was successfully updated.' }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: 'Office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def office_params
      params.require(:office).permit(:name, :location, :address)
    end
end

app/controllers/sows_controller.rb
class SowsController < ApplicationController
  before_action :set_sow, only: [:show, :edit, :update, :destroy]

  # GET /sows
  # GET /sows.json
  def index
    @sows = Sow.all
  end

  # GET /sows/1
  # GET /sows/1.json
  def show
  end

  # GET /sows/new
  def new
    @sow = Sow.new
  end

  # GET /sows/1/edit
  def edit
  end

  # POST /sows
  # POST /sows.json
  def create
    @sow = Sow.new(sow_params)

    respond_to do |format|
      if @sow.save
        format.html { redirect_to @sow, notice: 'Sow was successfully created.' }
        format.json { render :show, status: :created, location: @sow }
      else
        format.html { render :new }
        format.json { render json: @sow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sows/1
  # PATCH/PUT /sows/1.json
  def update
    respond_to do |format|
      if @sow.update(sow_params)
        format.html { redirect_to @sow, notice: 'Sow was successfully updated.' }
        format.json { render :show, status: :ok, location: @sow }
      else
        format.html { render :edit }
        format.json { render json: @sow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sows/1
  # DELETE /sows/1.json
  def destroy
    @sow.destroy
    respond_to do |format|
      format.html { redirect_to sows_url, notice: 'Sow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sow
      @sow = Sow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sow_params
      params.require(:sow).permit(:project_id, :A1_prop, :A1_est, :A2_prop, :A2_est, :SA_prop, :SA_est, :MGR_prop, :MGR_est, :MD_prop, :MD_est, :VP_prop, :VP_est, :PRES_prop, :PRES_est, :EXNET_prop, :EXNET_est, :OPS_prop, :OPS_est, :INT_prop, :INT_est)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sows_helper.rb
module SowsHelper
end

app/helpers/titan_roles_helper.rb
module TitanRolesHelper
end

app/helpers/titans_helper.rb
module TitansHelper
end

app/views/offices/_form.html.erb
<%= form_with(model: office, local: true) do |form| %>
  <% if office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
        <% office.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/offices/edit.html.erb
<h1>Editing Office</h1>

<%= render 'form', office: @office %>

<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

app/views/offices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offices.each do |office| %>
      <tr>
        <td><%= office.name %></td>
        <td><%= office.location %></td>
        <td><%= office.address %></td>
        <td><%= link_to 'Show', office %></td>
        <td><%= link_to 'Edit', edit_office_path(office) %></td>
        <td><%= link_to 'Destroy', office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Office', new_office_path %>

app/views/offices/new.html.erb
<h1>New Office</h1>

<%= render 'form', office: @office %>

<%= link_to 'Back', offices_path %>

app/views/offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @office.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @office.location %>
</p>

<p>
  <strong>Address:</strong>
  <%= @office.address %>
</p>

<%= link_to 'Edit', edit_office_path(@office) %> |
<%= link_to 'Back', offices_path %>