config/routes.rb
Rails.application.routes.draw do
  resources :categories
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :estimates
  resources :projects
  resources :project_titans
  resources :titan_roles
  resources :roles
  resources :sows
  resources :clients
  resources :titans
  resources :offices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :subcategories, :class_name => "Category", :foreign_key => "parent_id", :dependent => :destroy
  belongs_to :parent_category, :class_name => "Category", optional: true

   accepts_nested_attributes_for :subcategories
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :office, inverse_of: :clients
  has_many :projects, inverse_of: :client
end

app/models/estimate.rb
class Estimate < ApplicationRecord
  belongs_to :project, inverse_of: :estimate
end

app/models/office.rb
class Office < ApplicationRecord
	has_many :clients
	has_many :projects, through: :clients
	has_many :sows, through: :projects
	has_many :estimates, through: :projects


	has_many :titans

	enum name: {east: 'East Coast', west: 'West Coast', central: 'Dallas'}

end

app/models/project.rb
class Project < ApplicationRecord

  belongs_to :client, inverse_of: :projects
  has_one :sow, inverse_of: :project
  has_one :estimate, inverse_of: :project
  has_many :project_titans, inverse_of: :titan
  has_many :titans, through: :project_titans


  accepts_nested_attributes_for :sow, :estimate 

  enum phase: {
  	bd: 'BizDev', 
  	pitch: 'Pitched', 
  	negotiation: 'Drafting / SOW Negoiation', 
  	accepted: 'Accepted', 
  	in_progress: 'In Progress', 
  	complete: 'Completed', 
  	archived: 'Rejected'
  }

  enum category: {
    Strategy_Operationalization: 'Strategy Operationalization', 
    Operating_Model_Agility: 'Operating Model Agility', 
    Strategy_Development: 'Strategy Development', 
    Digital_and_Tech_Transformation: 'Digital & Tech Transformation', 
  }
  
end

app/models/project_titan.rb
class ProjectTitan < ApplicationRecord
  belongs_to :project
  belongs_to :titan
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :titan_roles
	has_many :titans, through: :titan_roles

end

app/models/sow.rb
class Sow < ApplicationRecord
  belongs_to :project, inverse_of: :sow
end

app/models/titan.rb
class Titan < ApplicationRecord
	belongs_to :office

	
	
	has_many :project_titans
	has_many :projects, through: :project_titans
	has_many :clients, through: :projects

	has_many :titan_roles
	has_many :roles, through: :titan_roles
end

app/models/titan_role.rb
class TitanRole < ApplicationRecord
  belongs_to :titan
  belongs_to :role
end

app/controllers/sows_controller.rb
class SowsController < ApplicationController
  before_action :set_sow, only: [:show, :edit, :update, :destroy]

  # GET /sows
  # GET /sows.json
  def index
    @sows = Sow.all
  end

  # GET /sows/1
  # GET /sows/1.json
  def show
  end

  # GET /sows/new
  def new
    @sow = Sow.new
  end

  # GET /sows/1/edit
  def edit
  end

  # POST /sows
  # POST /sows.json
  def create
    @sow = Sow.new(sow_params)

    respond_to do |format|
      if @sow.save
        format.html { redirect_to @sow, notice: 'Sow was successfully created.' }
        format.json { render :show, status: :created, location: @sow }
      else
        format.html { render :new }
        format.json { render json: @sow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sows/1
  # PATCH/PUT /sows/1.json
  def update
    respond_to do |format|
      if @sow.update(sow_params)
        format.html { redirect_to @sow, notice: 'Sow was successfully updated.' }
        format.json { render :show, status: :ok, location: @sow }
      else
        format.html { render :edit }
        format.json { render json: @sow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sows/1
  # DELETE /sows/1.json
  def destroy
    @sow.destroy
    respond_to do |format|
      format.html { redirect_to sows_url, notice: 'Sow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sow
      @sow = Sow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sow_params
      params.require(:sow).permit(:project_id, :A1_prop, :A1_est, :A2_prop, :A2_est, :SA_prop, :SA_est, :MGR_prop, :MGR_est, :MD_prop, :MD_est, :VP_prop, :VP_est, :PRES_prop, :PRES_est, :EXNET_prop, :EXNET_est, :OPS_prop, :OPS_est, :INT_prop, :INT_est)
    end
end

app/controllers/titans_controller.rb
class TitansController < ApplicationController
  before_action :set_titan, only: [:show, :edit, :update, :destroy]

  # GET /titans
  # GET /titans.json
  def index
    @titans = Titan.all
  end

  # GET /titans/1
  # GET /titans/1.json
  def show
  end

  # GET /titans/new
  def new
    @titan = Titan.new
  end

  # GET /titans/1/edit
  def edit
  end

  # POST /titans
  # POST /titans.json
  def create
    @titan = Titan.new(titan_params)

    respond_to do |format|
      if @titan.save
        format.html { redirect_to @titan, notice: 'Titan was successfully created.' }
        format.json { render :show, status: :created, location: @titan }
      else
        format.html { render :new }
        format.json { render json: @titan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /titans/1
  # PATCH/PUT /titans/1.json
  def update
    respond_to do |format|
      if @titan.update(titan_params)
        format.html { redirect_to @titan, notice: 'Titan was successfully updated.' }
        format.json { render :show, status: :ok, location: @titan }
      else
        format.html { render :edit }
        format.json { render json: @titan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /titans/1
  # DELETE /titans/1.json
  def destroy
    @titan.destroy
    respond_to do |format|
      format.html { redirect_to titans_url, notice: 'Titan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_titan
      @titan = Titan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def titan_params
      params.require(:titan).permit(:office_id, :name, :birthday, :hire_date, :phone, :address, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sows_helper.rb
module SowsHelper
end

app/helpers/titan_roles_helper.rb
module TitanRolesHelper
end

app/helpers/titans_helper.rb
module TitansHelper
end

app/views/titans/_form.html.erb
<%= form_with(model: titan, local: true) do |form| %>
  <% if titan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(titan.errors.count, "error") %> prohibited this titan from being saved:</h2>

      <ul>
        <% titan.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :office_id %>
    <%= form.text_field :office_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday %>
  </div>

  <div class="field">
    <%= form.label :hire_date %>
    <%= form.date_select :hire_date %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/titans/edit.html.erb
<h1>Editing Titan</h1>

<%= render 'form', titan: @titan %>

<%= link_to 'Show', @titan %> |
<%= link_to 'Back', titans_path %>

app/views/titans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Titans</h1>

<table>
  <thead>
    <tr>
      <th>Office</th>
      <th>Name</th>
      <th>Birthday</th>
      <th>Hire date</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @titans.each do |titan| %>
      <tr>
        <td><%= titan.office_id %></td>
        <td><%= titan.name %></td>
        <td><%= titan.birthday %></td>
        <td><%= titan.hire_date %></td>
        <td><%= titan.phone %></td>
        <td><%= titan.address %></td>
        <td><%= titan.email %></td>
        <td><%= link_to 'Show', titan %></td>
        <td><%= link_to 'Edit', edit_titan_path(titan) %></td>
        <td><%= link_to 'Destroy', titan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Titan', new_titan_path %>

app/views/titans/new.html.erb
<h1>New Titan</h1>

<%= render 'form', titan: @titan %>

<%= link_to 'Back', titans_path %>

app/views/titans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Office:</strong>
  <%= @titan.office_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @titan.name %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @titan.birthday %>
</p>

<p>
  <strong>Hire date:</strong>
  <%= @titan.hire_date %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @titan.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @titan.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @titan.email %>
</p>

<%= link_to 'Edit', edit_titan_path(@titan) %> |
<%= link_to 'Back', titans_path %>