config/routes.rb
Rails.application.routes.draw do
  resources :categories
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :estimates
  resources :projects
  resources :project_titans
  resources :titan_roles
  resources :roles
  resources :sows
  resources :clients
  resources :titans
  resources :offices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :subcategories, :class_name => "Category", :foreign_key => "parent_id", :dependent => :destroy
  belongs_to :parent_category, :class_name => "Category", optional: true

   accepts_nested_attributes_for :subcategories
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :office, inverse_of: :clients
  has_many :projects, inverse_of: :client
end

app/models/estimate.rb
class Estimate < ApplicationRecord
  belongs_to :project, inverse_of: :estimate
end

app/models/office.rb
class Office < ApplicationRecord
	has_many :clients
	has_many :projects, through: :clients
	has_many :sows, through: :projects
	has_many :estimates, through: :projects


	has_many :titans

	enum name: {east: 'East Coast', west: 'West Coast', central: 'Dallas'}

end

app/models/project.rb
class Project < ApplicationRecord

  belongs_to :client, inverse_of: :projects
  has_one :sow, inverse_of: :project
  has_one :estimate, inverse_of: :project
  has_many :project_titans, inverse_of: :titan
  has_many :titans, through: :project_titans


  accepts_nested_attributes_for :sow, :estimate 

  enum phase: {
  	bd: 'BizDev', 
  	pitch: 'Pitched', 
  	negotiation: 'Drafting / SOW Negoiation', 
  	accepted: 'Accepted', 
  	in_progress: 'In Progress', 
  	complete: 'Completed', 
  	archived: 'Rejected'
  }

  enum category: {
    Strategy_Operationalization: 'Strategy Operationalization', 
    Operating_Model_Agility: 'Operating Model Agility', 
    Strategy_Development: 'Strategy Development', 
    Digital_and_Tech_Transformation: 'Digital & Tech Transformation', 
  }
  
end

app/models/project_titan.rb
class ProjectTitan < ApplicationRecord
  belongs_to :project
  belongs_to :titan
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :titan_roles
	has_many :titans, through: :titan_roles

end

app/models/sow.rb
class Sow < ApplicationRecord
  belongs_to :project, inverse_of: :sow
end

app/models/titan.rb
class Titan < ApplicationRecord
	belongs_to :office

	
	
	has_many :project_titans
	has_many :projects, through: :project_titans
	has_many :clients, through: :projects

	has_many :titan_roles
	has_many :roles, through: :titan_roles
end

app/models/titan_role.rb
class TitanRole < ApplicationRecord
  belongs_to :titan
  belongs_to :role
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:client_id, :name, :category, :subcategory, :start, :end)
    end
end

app/controllers/sows_controller.rb
class SowsController < ApplicationController
  before_action :set_sow, only: [:show, :edit, :update, :destroy]

  # GET /sows
  # GET /sows.json
  def index
    @sows = Sow.all
  end

  # GET /sows/1
  # GET /sows/1.json
  def show
  end

  # GET /sows/new
  def new
    @sow = Sow.new
  end

  # GET /sows/1/edit
  def edit
  end

  # POST /sows
  # POST /sows.json
  def create
    @sow = Sow.new(sow_params)

    respond_to do |format|
      if @sow.save
        format.html { redirect_to @sow, notice: 'Sow was successfully created.' }
        format.json { render :show, status: :created, location: @sow }
      else
        format.html { render :new }
        format.json { render json: @sow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sows/1
  # PATCH/PUT /sows/1.json
  def update
    respond_to do |format|
      if @sow.update(sow_params)
        format.html { redirect_to @sow, notice: 'Sow was successfully updated.' }
        format.json { render :show, status: :ok, location: @sow }
      else
        format.html { render :edit }
        format.json { render json: @sow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sows/1
  # DELETE /sows/1.json
  def destroy
    @sow.destroy
    respond_to do |format|
      format.html { redirect_to sows_url, notice: 'Sow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sow
      @sow = Sow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sow_params
      params.require(:sow).permit(:project_id, :A1_prop, :A1_est, :A2_prop, :A2_est, :SA_prop, :SA_est, :MGR_prop, :MGR_est, :MD_prop, :MD_est, :VP_prop, :VP_est, :PRES_prop, :PRES_est, :EXNET_prop, :EXNET_est, :OPS_prop, :OPS_est, :INT_prop, :INT_est)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sows_helper.rb
module SowsHelper
end

app/helpers/titan_roles_helper.rb
module TitanRolesHelper
end

app/helpers/titans_helper.rb
module TitansHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.text_field :client_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :subcategory %>
    <%= form.text_field :subcategory %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.date_select :start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.date_select :end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Name</th>
      <th>Category</th>
      <th>Subcategory</th>
      <th>Start</th>
      <th>End</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.client_id %></td>
        <td><%= project.name %></td>
        <td><%= project.category %></td>
        <td><%= project.subcategory %></td>
        <td><%= project.start %></td>
        <td><%= project.end %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @project.client_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @project.category %>
</p>

<p>
  <strong>Subcategory:</strong>
  <%= @project.subcategory %>
</p>

<p>
  <strong>Start:</strong>
  <%= @project.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @project.end %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>