config/routes.rb
Rails.application.routes.draw do
  resources :categories
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :estimates
  resources :projects
  resources :project_titans
  resources :titan_roles
  resources :roles
  resources :sows
  resources :clients
  resources :titans
  resources :offices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :subcategories, :class_name => "Category", :foreign_key => "parent_id", :dependent => :destroy
  belongs_to :parent_category, :class_name => "Category", optional: true

   accepts_nested_attributes_for :subcategories
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :office, inverse_of: :clients
  has_many :projects, inverse_of: :client
end

app/models/estimate.rb
class Estimate < ApplicationRecord
  belongs_to :project, inverse_of: :estimate
end

app/models/office.rb
class Office < ApplicationRecord
	has_many :clients
	has_many :projects, through: :clients
	has_many :sows, through: :projects
	has_many :estimates, through: :projects


	has_many :titans

	enum name: {east: 'East Coast', west: 'West Coast', central: 'Dallas'}

end

app/models/project.rb
class Project < ApplicationRecord

  belongs_to :client, inverse_of: :projects
  has_one :sow, inverse_of: :project
  has_one :estimate, inverse_of: :project
  has_many :project_titans, inverse_of: :titan
  has_many :titans, through: :project_titans


  accepts_nested_attributes_for :sow, :estimate 

  enum phase: {
  	bd: 'BizDev', 
  	pitch: 'Pitched', 
  	negotiation: 'Drafting / SOW Negoiation', 
  	accepted: 'Accepted', 
  	in_progress: 'In Progress', 
  	complete: 'Completed', 
  	archived: 'Rejected'
  }

  enum category: {
    Strategy_Operationalization: 'Strategy Operationalization', 
    Operating_Model_Agility: 'Operating Model Agility', 
    Strategy_Development: 'Strategy Development', 
    Digital_and_Tech_Transformation: 'Digital & Tech Transformation', 
  }
  
end

app/models/project_titan.rb
class ProjectTitan < ApplicationRecord
  belongs_to :project
  belongs_to :titan
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :titan_roles
	has_many :titans, through: :titan_roles

end

app/models/sow.rb
class Sow < ApplicationRecord
  belongs_to :project, inverse_of: :sow
end

app/models/titan.rb
class Titan < ApplicationRecord
	belongs_to :office

	
	
	has_many :project_titans
	has_many :projects, through: :project_titans
	has_many :clients, through: :projects

	has_many :titan_roles
	has_many :roles, through: :titan_roles
end

app/models/titan_role.rb
class TitanRole < ApplicationRecord
  belongs_to :titan
  belongs_to :role
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:title, :daily_rate)
    end
end

app/controllers/sows_controller.rb
class SowsController < ApplicationController
  before_action :set_sow, only: [:show, :edit, :update, :destroy]

  # GET /sows
  # GET /sows.json
  def index
    @sows = Sow.all
  end

  # GET /sows/1
  # GET /sows/1.json
  def show
  end

  # GET /sows/new
  def new
    @sow = Sow.new
  end

  # GET /sows/1/edit
  def edit
  end

  # POST /sows
  # POST /sows.json
  def create
    @sow = Sow.new(sow_params)

    respond_to do |format|
      if @sow.save
        format.html { redirect_to @sow, notice: 'Sow was successfully created.' }
        format.json { render :show, status: :created, location: @sow }
      else
        format.html { render :new }
        format.json { render json: @sow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sows/1
  # PATCH/PUT /sows/1.json
  def update
    respond_to do |format|
      if @sow.update(sow_params)
        format.html { redirect_to @sow, notice: 'Sow was successfully updated.' }
        format.json { render :show, status: :ok, location: @sow }
      else
        format.html { render :edit }
        format.json { render json: @sow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sows/1
  # DELETE /sows/1.json
  def destroy
    @sow.destroy
    respond_to do |format|
      format.html { redirect_to sows_url, notice: 'Sow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sow
      @sow = Sow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sow_params
      params.require(:sow).permit(:project_id, :A1_prop, :A1_est, :A2_prop, :A2_est, :SA_prop, :SA_est, :MGR_prop, :MGR_est, :MD_prop, :MD_est, :VP_prop, :VP_est, :PRES_prop, :PRES_est, :EXNET_prop, :EXNET_est, :OPS_prop, :OPS_est, :INT_prop, :INT_est)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sows_helper.rb
module SowsHelper
end

app/helpers/titan_roles_helper.rb
module TitanRolesHelper
end

app/helpers/titans_helper.rb
module TitansHelper
end

app/views/roles/_form.html.erb
<%= form_with(model: role, local: true) do |form| %>
  <% if role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
        <% role.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :daily_rate %>
    <%= form.text_field :daily_rate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Daily rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.title %></td>
        <td><%= role.daily_rate %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @role.title %>
</p>

<p>
  <strong>Daily rate:</strong>
  <%= @role.daily_rate %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/sows/_form.html.erb
<%= form_with(model: sow, local: true) do |form| %>
  <% if sow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sow.errors.count, "error") %> prohibited this sow from being saved:</h2>

      <ul>
        <% sow.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id %>
  </div>

  <div class="field">
    <%= form.label :A1_prop %>
    <%= form.text_field :A1_prop %>
  </div>

  <div class="field">
    <%= form.label :A1_est %>
    <%= form.text_field :A1_est %>
  </div>

  <div class="field">
    <%= form.label :A2_prop %>
    <%= form.text_field :A2_prop %>
  </div>

  <div class="field">
    <%= form.label :A2_est %>
    <%= form.text_field :A2_est %>
  </div>

  <div class="field">
    <%= form.label :SA_prop %>
    <%= form.text_field :SA_prop %>
  </div>

  <div class="field">
    <%= form.label :SA_est %>
    <%= form.text_field :SA_est %>
  </div>

  <div class="field">
    <%= form.label :MGR_prop %>
    <%= form.text_field :MGR_prop %>
  </div>

  <div class="field">
    <%= form.label :MGR_est %>
    <%= form.text_field :MGR_est %>
  </div>

  <div class="field">
    <%= form.label :MD_prop %>
    <%= form.text_field :MD_prop %>
  </div>

  <div class="field">
    <%= form.label :MD_est %>
    <%= form.text_field :MD_est %>
  </div>

  <div class="field">
    <%= form.label :VP_prop %>
    <%= form.text_field :VP_prop %>
  </div>

  <div class="field">
    <%= form.label :VP_est %>
    <%= form.text_field :VP_est %>
  </div>

  <div class="field">
    <%= form.label :PRES_prop %>
    <%= form.text_field :PRES_prop %>
  </div>

  <div class="field">
    <%= form.label :PRES_est %>
    <%= form.text_field :PRES_est %>
  </div>

  <div class="field">
    <%= form.label :EXNET_prop %>
    <%= form.text_field :EXNET_prop %>
  </div>

  <div class="field">
    <%= form.label :EXNET_est %>
    <%= form.text_field :EXNET_est %>
  </div>

  <div class="field">
    <%= form.label :OPS_prop %>
    <%= form.text_field :OPS_prop %>
  </div>

  <div class="field">
    <%= form.label :OPS_est %>
    <%= form.text_field :OPS_est %>
  </div>

  <div class="field">
    <%= form.label :INT_prop %>
    <%= form.text_field :INT_prop %>
  </div>

  <div class="field">
    <%= form.label :INT_est %>
    <%= form.text_field :INT_est %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sows/edit.html.erb
<h1>Editing Sow</h1>

<%= render 'form', sow: @sow %>

<%= link_to 'Show', @sow %> |
<%= link_to 'Back', sows_path %>

app/views/sows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sows</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>A1 prop</th>
      <th>A1 est</th>
      <th>A2 prop</th>
      <th>A2 est</th>
      <th>Sa prop</th>
      <th>Sa est</th>
      <th>Mgr prop</th>
      <th>Mgr est</th>
      <th>Md prop</th>
      <th>Md est</th>
      <th>Vp prop</th>
      <th>Vp est</th>
      <th>Pres prop</th>
      <th>Pres est</th>
      <th>Exnet prop</th>
      <th>Exnet est</th>
      <th>Ops prop</th>
      <th>Ops est</th>
      <th>Int prop</th>
      <th>Int est</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sows.each do |sow| %>
      <tr>
        <td><%= sow.project_id %></td>
        <td><%= sow.A1_prop %></td>
        <td><%= sow.A1_est %></td>
        <td><%= sow.A2_prop %></td>
        <td><%= sow.A2_est %></td>
        <td><%= sow.SA_prop %></td>
        <td><%= sow.SA_est %></td>
        <td><%= sow.MGR_prop %></td>
        <td><%= sow.MGR_est %></td>
        <td><%= sow.MD_prop %></td>
        <td><%= sow.MD_est %></td>
        <td><%= sow.VP_prop %></td>
        <td><%= sow.VP_est %></td>
        <td><%= sow.PRES_prop %></td>
        <td><%= sow.PRES_est %></td>
        <td><%= sow.EXNET_prop %></td>
        <td><%= sow.EXNET_est %></td>
        <td><%= sow.OPS_prop %></td>
        <td><%= sow.OPS_est %></td>
        <td><%= sow.INT_prop %></td>
        <td><%= sow.INT_est %></td>
        <td><%= link_to 'Show', sow %></td>
        <td><%= link_to 'Edit', edit_sow_path(sow) %></td>
        <td><%= link_to 'Destroy', sow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sow', new_sow_path %>

app/views/sows/new.html.erb
<h1>New Sow</h1>

<%= render 'form', sow: @sow %>

<%= link_to 'Back', sows_path %>

app/views/sows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @sow.project_id %>
</p>

<p>
  <strong>A1 prop:</strong>
  <%= @sow.A1_prop %>
</p>

<p>
  <strong>A1 est:</strong>
  <%= @sow.A1_est %>
</p>

<p>
  <strong>A2 prop:</strong>
  <%= @sow.A2_prop %>
</p>

<p>
  <strong>A2 est:</strong>
  <%= @sow.A2_est %>
</p>

<p>
  <strong>Sa prop:</strong>
  <%= @sow.SA_prop %>
</p>

<p>
  <strong>Sa est:</strong>
  <%= @sow.SA_est %>
</p>

<p>
  <strong>Mgr prop:</strong>
  <%= @sow.MGR_prop %>
</p>

<p>
  <strong>Mgr est:</strong>
  <%= @sow.MGR_est %>
</p>

<p>
  <strong>Md prop:</strong>
  <%= @sow.MD_prop %>
</p>

<p>
  <strong>Md est:</strong>
  <%= @sow.MD_est %>
</p>

<p>
  <strong>Vp prop:</strong>
  <%= @sow.VP_prop %>
</p>

<p>
  <strong>Vp est:</strong>
  <%= @sow.VP_est %>
</p>

<p>
  <strong>Pres prop:</strong>
  <%= @sow.PRES_prop %>
</p>

<p>
  <strong>Pres est:</strong>
  <%= @sow.PRES_est %>
</p>

<p>
  <strong>Exnet prop:</strong>
  <%= @sow.EXNET_prop %>
</p>

<p>
  <strong>Exnet est:</strong>
  <%= @sow.EXNET_est %>
</p>

<p>
  <strong>Ops prop:</strong>
  <%= @sow.OPS_prop %>
</p>

<p>
  <strong>Ops est:</strong>
  <%= @sow.OPS_est %>
</p>

<p>
  <strong>Int prop:</strong>
  <%= @sow.INT_prop %>
</p>

<p>
  <strong>Int est:</strong>
  <%= @sow.INT_est %>
</p>

<%= link_to 'Edit', edit_sow_path(@sow) %> |
<%= link_to 'Back', sows_path %>